name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      TEST_SCOPE: full

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (stable)
        if: env.TEST_SCOPE == 'stable'
        run: npm run test:ci

      - name: Run Cypress tests (full)
        if: env.TEST_SCOPE == 'full'
        run: npm run test:ci:full

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report 
          path: cypress/reports/mochawesome